### ISSUE TITLE
Web part not initializing

### ISSUE THREAD

**Issue by cni13** [wobba/spfx4fun#1]
I followed the instructions on the readme and added the app to a site. Then I tried to add the web part to a modern page. After some seconds I get this error and the web part fails to load:

"Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.

Technical Details
[SPWebPartErrorCode.ScriptLoadError]: Unable to load web part WebPart.SitePageHeaderConfiguratorWebPart.cd10ac58-7e64-40e4-b100-1268153c8914,Error: ***Failed to load component "ed5bdd3b-c869-4d76-9cd3-0de041339898" (SitePageHeaderConfiguratorWebPart). 

Original error: ***Failed to load URL 'https://localhost:4321/lib/webparts/sitePageHeaderConfigurator/loc/en-us.js' for resource 'sitePageHeaderConfiguratorStrings' in component 'ed5bdd3b-c869-4d76-9cd3-0de041339898' (SitePageHeaderConfiguratorWebPart). There was a network problem. Make sure that you have run 'gulp trust-dev-cert'. script resources due to: {1}. ***CALLSTACK: Error at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/sp-loader_en-us_d3fcdc7e13606303cccca7047ff4e32a.js:88:24935) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/sp-webpart-base_en-us_67dad9189b6a5af799dda7420c84171d.js:146:25334) at t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/sp-webpart-base_en-us_67dad9189b6a5af799dda7420c84171d.js:146:25776) at e.prototype._handleModulePromiseRejection (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/sp-webpart-base_en-us_67dad9189b6a5af799dda7420c84171d.js:146:57106) at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/sp-webpart-base_en-us_67dad9189b6a5af799dda7420c84171d.js:146:47253)"

Whats the solution to the issue?

**Comment by doctorvanya** [comment]
+1 the same problem!
bad path  error (https://localhost:4321)
